### ISSUE TITLE
Does not work with PF1E System

### ISSUE THREAD

**Issue by maxipad1991junkmail** [schultzcole/FVTT-Wall-Height#13]
I really loved this module previously (and my players loved it too!) but it seems it no longer works with the PF1E system.  Is there any chance that this could be fixed?

**Comment by schultzcole** [comment]
Thanks for creating this issue. This is a known issue (I know Tarbarian on the foundry discord has been on my case about re-adding PF1E support), but I haven't gotten the chance to address it yet. I can't make any promises about timing as I have other projects that are more urgent for me personally.

I definitely have it in mind, and once again thank you for creating this issue so that it's on record as a desired feature.

**Comment by Tarbarian** [comment]
So I figured rather than getting on your case on Discord (sorry...) I would go ahead and post here. Strangely enough the module seems to work the same for PF1e as it does for other systems (Tested with PF2e and Starfinder).

**Comment by schultzcole** [comment]
Yeah I did notice that there was some discussion about a few issues in the pf1e chat and it seemed like all of the issues that were mentioned were not pf1e specific. In fact I reopened some older github tickets for those problems after reading that discussion so I think this specific ticket is not needed because the actual problems are captured in more specific tickets unrelated to pf1e. I'm closing this ticket for that reason, but feel free to continue discussion here if you have questions or other comments related to pf1e specifically.

@maxipad1991junkmail can you verify whether the other open github tickets cover all of the issues you have encountered? If there are specific issues that are not covered by those, I would request that you make a more specific ticket for each individual problem.
